# Pipeline Principal - Coordena todos os workflows
name: CI/CD Pipeline

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        branches:
            - develop
            - main

jobs:
    # Este job serve apenas para mostrar o status geral da pipeline
    pipeline-status:
        runs-on: ubuntu-latest

        steps:
            - name: Pipeline Status
              run: |
                  echo "🚀 CI/CD Pipeline iniciada!"
                  echo "📋 Workflows executando:"
                  echo "  ✅ Tests (test.yml)"
                  echo "  ✅ Code Quality (quality.yml)" 
                  echo "  ✅ Deploy (deploy.yml)"
                  echo ""
                  echo "📊 Verifique o status de cada workflow na aba Actions"
